### ISSUE TITLE
Feature: Expansion Pathbuilder

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/dfg_3dviewer#1]
* [x] Expansion of the pathbuilder to full documentation format according to miro-board documentation scheme

**Comment by igorbajena** [comment]
Documentation scheme is upgraded. Review needs to be done, what kind of fields can be implemented without system destruction

**Comment by ClemensBeck** [comment]
Igor: "Postponed to CoVHER project"

**Comment by ClemensBeck** [comment]
@igorbajena Since I'm migrating all the isuses to the new github repo. Is this isue still open?

**Comment by igorbajena** [comment]
Can be closed, I'm working on it currently in CoVher Repository - we'll be done in next few weeks
