### ISSUE TITLE
Bug: Wrong naming while Uploading 

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/dfg_3dviewer#13]
* [ ] @thedworak Wrong naming while uploading part of the building, like window, arch, etc. No possibility to add semantically those parts in data model.

**Comment by thedworak** [comment]
PHP code on Drupal module is finished, need more time to prepare it on viewer side

**Comment by igorbajena** [comment]
Problem was solved with help of Mark

**Comment by ClemensBeck** [comment]
Igor updated it and need to further work on it

**Comment by igorbajena** [comment]
I've added possibility of adding models parts, version, or derivatives with field for addition to the name
