### ISSUE TITLE
Bug: UX Interface

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/dfg_3dviewer#16]
* [x] Fix the Bug regarding the Controls from https://github.com/thedworak/3D-DFG-Viewer/issues/15

**Information about it (see https://github.com/thedworak/3D-DFG-Viewer/issues/15):** 

Hi again,

attached to this comment you find the same documents as above, this time in english. 

If some of my translations failed, just let me know. 

Also my "coding system" is explained in the headline of each column, e.g. "Control bar on the right (0=position ideal; 1=position not ideal)".

If you have any questions please feel free to ask.

Best
Constantin
[3D Repository Test_english.xlsx](https://github.com/thedworak/3D-DFG-Viewer/files/9442687/3D.Repository.Test_english.xlsx)
![After quitting full screen, position of control bar is ideal_after quitting full screen mode](https://user-images.githubusercontent.com/112182069/187152791-466e5057-b238-48e0-aad3-2a70857a6306.png)
![After quitting full screen, position of control bar is ideal_before full screen mode](https://user-images.githubusercontent.com/112182069/187152795-dc73c1d8-32e9-41b0-abb9-22fdef7e95b7.png)
![Download button and share button too close in full screen mode_full screen mode](https://user-images.githubusercontent.com/112182069/187152799-45fece97-068c-46e6-b14b-ae439cfb1037.png)
![Download button and share button too close in full screen mode_normal mode](https://user-images.githubusercontent.com/112182069/187152802-66334d84-ad82-4eaa-9b6c-2d8e7af2628e.png)
![Entire page can be moved to the left (randomly tested)_moved](https://user-images.githubusercontent.com/112182069/187152803-2718cafc-93d3-4208-9e16-5c881fa69631.png)
![Entire page can be moved to the left (randomly tested)_normal](https://user-images.githubusercontent.com/112182069/187152806-7b19f2aa-e7aa-4bd2-9f90-d9714e163a0d.png)

_Originally posted by @CKFSU in https://github.com/thedworak/3D-DFG-Viewer/issues/15#issuecomment-1229916556_
_____________________________________________________
Hi again again, 

I randomly tested some models again, always some for each browser and all the ones that didn’t load in the first place. For some reason they still don’t work (see the newest column on the right in the excel sheet). Maybe it’s because of my mac or browser versions. 

As Clemens asked me to, here are the informations:

- Software: macOS Monterey 12.1
- Browser Versions:
      Chrome: 105.0.5195.52 (downloaded today)
      Edge: 105.0.1343.25 (downloaded today)
      Firefox: 91.13.0esr (64-Bit)
      Opera: 90.0.4480.80 (x86_64)
      Safari: 15.2 (17612.3.6.1.6)
- Mac Book Air 13’’ (2015), Resolution (default setting): 1440 x 900 

I hope that helps. Let me know if not.

Best 
Constantin

[3D Repository Test_english_20220902.xlsx](https://github.com/thedworak/3D-DFG-Viewer/files/9476271/3D.Repository.Test_english_20220902.xlsx)

**Comment by thedworak** [comment]
![image](https://github.com/thedworak/dfg_3dviewer/assets/96061043/12b478f6-6317-44e9-9c32-f42cb27c8fdb)
new UI, needs to be tested more

**Comment by ClemensBeck** [comment]
@thedworak It is working fine on my computer! Many thanks!

**Comment by ClemensBeck** [comment]
Issue war moved to https://github.com/slub/dlf-3d-viewers/issues/20
