### ISSUE TITLE
Bug: Point cloud not visible in the viewer

### ISSUE THREAD

**Issue by igorbajena** [thedworak/dfg_3dviewer#18]
Lately, our colleague Karol Argasiński tried to upload a point cloud model to the repository. The model is not visible in the viewer. During further investigation of this issue we should keep in mind updating guidelines and prepare them also for point cloud models.
[](
https://3d-repository.hs-mainz.de/wisski/navigate/565/view?wisski_bundle=bd3d7baa74856d141bcff7b4193fa128)

![obraz](https://user-images.githubusercontent.com/109960112/189539421-5a56c3af-8c4d-4d20-9485-aa9c8cc01436.png)

![obraz](https://user-images.githubusercontent.com/109960112/189539447-b9236630-2279-4ac4-8362-c016da4a3398.png)

**Comment by thedworak** [comment]
Discussed with Igor, PLY Loader of three.js doesn't support loading of files containing properties of vertices. Only supports th positions of 3D points (x, y, z).
Here is working sample:
https://3d-repository.hs-mainz.de/wisski/navigate/573/view?wisski_bundle=bd3d7baa74856d141bcff7b4193fa128

**Comment by igorbajena** [comment]
New file was exported with just information about points position (no colour or shading information): https://3d-repository.hs-mainz.de/wisski/navigate/565/view

 After loading bar hits 100% the website sopped responding:

![image](https://user-images.githubusercontent.com/109960112/199213450-99638bad-1df4-473e-a419-4e17585934ae.png)

Then metadata are displayed in the viewer, but 3D model is still not visible. 
While file should be exported properly now, there should be some other limitations, which we should identify.

**Comment by igorbajena** [comment]
Problem solved, XYZ must be exported with only values for positioning the points. This case should be documented in Google Doc.
