### ISSUE TITLE
Feature: Adding Geocoordinates

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/dfg_3dviewer#2]
* [ ] Adding Geo-Coordinates
  * [x]  Go through instructions from PeG about geo-module
  * [x] Install new feature - DONE
  * [x] Adjust new feature with PeG

**Comment by ClemensBeck** [comment]
@igorbajena Since I'm migrating all the isuses to the new github repo. Is this isue still open?

**Comment by igorbajena** [comment]
I already figure this out. It can be closed

**Comment by ClemensBeck** [comment]
@igorbajena Okay, all right! I will close it.
