### ISSUE TITLE
Bug: Blank field when creating multiple entries in same category 

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/dfg_3dviewer#23]
* [ ] @igorbajena Fix the mentioned bug 

Feedback from Tassilo Striedl (LMU): 
"When creating wisski entries, specifically when creating multiple entries in the same category, such as more than one author, the information in the title field is displayed as blank after pressing the button to create another entry. The information is still documented and uploaded correctly, but is no longer visible on the overview during the upload process. Pressing the edit button also caused this to happen to the second entry, resulting in two entries being seen in the overview list with blank title fields."

**Comment by ClemensBeck** [comment]
@igorbajena Since I'm migrating all the isuses to the new github repo. Is this isue still open?

**Comment by igorbajena** [comment]
This is still open.

**Comment by ClemensBeck** [comment]
@igorbajena Ok. I moved the issue to the new repo: https://github.com/slub/dlf-3d-viewers/issues/21
