### ISSUE TITLE
Feature: Add History of Uploads

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/dfg_3dviewer#25]
* [x] @igorbajena Add History of Model Uploads 
Feedback from Tassilo Striedl (LMU):
" - There is no function available that you can see in your account which models you have already uploaded (so in a way a history of uploaded models) to make changes if necessary."

**Comment by igorbajena** [comment]
It needs consulations with drupal experts. Not possible in this phase of project.

**Comment by igorbajena** [comment]
After some investigation I was able to add list of uploaded models to the user account page. However, it is connected with publisher fields from upload form, so if someone didn't assign it properly, it could have not display all the models. It also needs a manual assignment of the person entry in database with user account. I've added possibility to create user wisski entry in database for newcomers during registration, but old accounts need to be assigned manually.
