### ISSUE TITLE
Bug: Integration with DFG-Viewer breaks because of absolute paths

### ISSUE THREAD

**Issue by sebastian-meyer** [thedworak/dfg_3dviewer#26]
In `main/main.js` all but one includes are handled as relative paths and work fine when integrating with the DFG-Viewer. But this include uses an absolute path which is only valid in Drupal/WissKI and therefore breaks integration:
https://github.com/thedworak/dfg_3dviewer/blob/72368981a5b6ca4f10e54db1d5678acb82aa141a/main/main.js#L27
Is there a reason for this being an absolute path or could it be a relative path as well?

I suggest changing it like:
`import { GUI } from './node_modules/lil-gui/dist/lil-gui.esm.min.js';`

Furthermore, when I change this locally, there are multiple additional absolute include paths in the library files (e. g. `three.module.js` and `GLTFLoader.js`) which also break integration.

**Comment by thedworak** [comment]
There is no problem to do this this way, probably I just missed this library when changing paths
`import { GUI } from './node_modules/lil-gui/dist/lil-gui.esm.min.js';`

The problem with three.js newest version is they started using importmap which is not supported by Drupal we are using. I stared implementation with default paths but it's not possible inside Drupal yet.

**Comment by sebastian-meyer** [comment]
So maybe the best option for us would be to use the original release of three.js in the DFG-Viewer and combine that with your `main.js` file? If I put all the original files in the correct locations given in the "include"s in `main.js` that should work, right?

**Comment by sebastian-meyer** [comment]
I just saw that three.js includes an `lil-gui` library. So maybe we could make things even easier and use

`include { GUI } from './js/jsm/libs/lil-gui.module.min.js';`

instead of the import from `node_modules` directory?

**Comment by sebastian-meyer** [comment]
Now I got a bit further:
- made the include of `lil-gui.module.min.js` in `main.js` relative (as mentioned above
- added `main.js` and `spinner/*` from your repository to the DFG-Viewer
- added `build/*` and `examples/jsm` (as `js/jsm`) from the officiel r145 release of three.js to the DFG-Viewer
- added an `importmap` statement as requirement by three.js to the DFG-Viewer

So far this seems to work. But there are still paths in your `main.js` that are only valid in the Drupal context and don't work in the DFG-Viewer. Currently you are passing paths like `module/dfg_3dviewer/main/*` to some of the three.js modules, which don't exist in the DFG-Viewer. Instead, there the paths should be like `typo3conf/ext/dlf/Resources/Public/Javascript/3DViewer/*`. Can we find a way of making at least the prefix configurable? If you like, I can provide a pull request.

**Comment by thedworak** [comment]
Great to hear it. Could you please check the newest code then? I just added some more things and made code cleanup.

**Comment by sebastian-meyer** [comment]
Your latest code is now deployed here (without any changes): https://3dtest.dfg-viewer.de/viewer?tx_dlf[id]=https://4dcity.org/modelupload/70ef075a31ef44ac97bc1459baee7a18/70ef075a31ef44ac97bc1459baee7a18metsmods.xml&no_cache=1

**Comment by sebastian-meyer** [comment]
Now I deployed my code with the changes from #27 and configured `CONFIG.basePath` according to my environment. Good news is: the viewer gets to the point where it tries to load the gltf file, now. Bad news: this fails, but I don't know why (the errors point to `three.module.js` and `GLTFLoader.js`). Could you please take it from here?

**Comment by ClemensBeck** [comment]
@thedworak Have you made any progress in solving the problem?

**Comment by sebastian-meyer** [comment]
No, but I also didn't investigate this any further. I debugged the code as far as integration with the DFG-Viewer is concerned. Now it seems to be issues with the viewer itself, so you are the expert for that. ;o)

**Comment by ClemensBeck** [comment]
Discussion on jour fixe: @thedworak will solve this in coming weeks

**Comment by ClemensBeck** [comment]
@sebastian-meyer Daniel solved the problem. Could you please check it?

**Comment by sebastian-meyer** [comment]
Unfortunately it's still not working.

The viewer still tries to load something from the Mainz repository even when loading a model from Jena. According to the JS console it tries to access https://3d-repository.hs-mainz.de/export_xml_single/?page=0&amp;_format=xml (which results in a 500 error) and then calls for https://4dcity.org/modelupload/600db4895c834276a4f667609fec89a4/metadata/600db4895c834276a4f667609fec89a4.gltf_viewer (which doesn't exist either). Subsequentely loading fails completely and nothing is shown.

I tested with this [example](https://3dtest.dfg-viewer.de/viewer?tx_dlf[id]=https://4dcity.org/modelupload/600db4895c834276a4f667609fec89a4/600db4895c834276a4f667609fec89a4metsmods.xml&no_cache=1). The model itself seems fine, because it works [with model-viewer](https://3dtest.dfg-viewer.de/viewer?tx_dlf[id]=https://4dcity.org/modelupload/600db4895c834276a4f667609fec89a4/600db4895c834276a4f667609fec89a4metsmods.xml&no_cache=1&modelviewer=1) (apart from missing support for glossy materials).

Again: I think we still need to get rid of all the code inside the viewer which is specific for the Mainz repository. This should be placed into a separate module which then can be used in WissKI, but omitted in the DFG-Viewer.

**Comment by thedworak** [comment]
Did you try to use lightweight version of the viewer?

**Comment by ClemensBeck** [comment]
@thedworak Will do this until next week

**Comment by thedworak** [comment]
I think it should be resolved

**Comment by ClemensBeck** [comment]
@sebastian-meyer Could you please check it?

**Comment by sebastian-meyer** [comment]
Unfortunately the latest changes seem to be a step backwards, because now nothing is shown at all. There are no errors in the console, but also no model shown. The loading indicator stays at 0%.

Examples:
https://3dtest.dfg-viewer.de/viewer?tx_dlf%5Bid%5D=https://4dcity.org/modelupload/600db4895c834276a4f667609fec89a4/600db4895c834276a4f667609fec89a4metsmods.xml&no_cache=1
https://3dtest.dfg-viewer.de/viewer?tx_dlf[id]=https://4dcity.org/modelupload/82bc2e1eb1a54e21bcff27c1d6b6d037/82bc2e1eb1a54e21bcff27c1d6b6d037metsmods.xml&no_cache=1
https://3dtest.dfg-viewer.de/viewer?tx_dlf[id]=https://4dcity.org/modelupload/4da20a3452394b489caec95fe6b0fc9f/4da20a3452394b489caec95fe6b0fc9fmetsmods.xml&no_cache=1

**Comment by sebastian-meyer** [comment]
The main.js I use can be found here: https://3dtest.dfg-viewer.de/typo3conf/ext/dlf/Resources/Public/Javascript/3DViewer/main.js

**Comment by thedworak** [comment]
Could you please @sebastian-meyer take a look right now?

**Comment by sebastian-meyer** [comment]
@thedworak Now the viewer displays the base reference system, but no model. There is an error in the console, which may be related?

**Comment by sebastian-meyer** [comment]
That didn't change anything, unfortunately...

**Comment by sebastian-meyer** [comment]
Ignore my last (deleted) comment! I forgot to purge the cache...

Now it's working! Thank you very much! I'll close this issue.
