### ISSUE TITLE
Feature: Adding Privatmode 

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/dfg_3dviewer#3]
* [ ] Adding Privat-Mode
  * [ ] Install the Published/Unblished Module which allows user to store data in private mode
Postponed until after releas?

**Comment by igorbajena** [comment]
From what I found out, it is possible to do. I would need find a proper module and ask Mark for its installation

**Comment by igorbajena** [comment]
I've added possibility to hide models from browse tab. User is still able to see it in his user account. Also administrators can see it in special navigate view accessible only for administrators.
