### ISSUE TITLE
[!] BUG: Support of Blender files

### ISSUE THREAD

**Issue by igorbajena** [thedworak/dfg_3dviewer#30]
We indicated that .blend files should be displayed in the viewer, but they are not.

Entry from the survey: "the description says .blend files should work, but when uploading it shows nothing"
https://3d-repository.hs-mainz.de/wisski/navigate/2074/view

Should we delete .blend from list of supported formats?

**Comment by thedworak** [comment]
This file cannot be exported into glTF, but I have no idea why.

**Comment by ClemensBeck** [comment]
Decision: Delete it from the list of supported formats (@igorbajena )

**Comment by igorbajena** [comment]
BLEND format was deleted from description of the file ulpoad, from the list of supported formats and from our guidelines. 

Many of entries, which declare BLEND format didn't upload it as format for the viewer but just as native file in order for storing. Due to this fact, creation of the previews was not possible. Do we want to have entries without viewer, just with storage of 3D files in native format?

**Comment by ClemensBeck** [comment]
Decision: Want to store native files, someone has to upload a screenshot of the model (Clemens will ask Liv for that)
