### ISSUE TITLE
Feature: Model rotation for a certain degree (e.g. 90 degrees) 

### ISSUE THREAD

**Issue by igorbajena** [thedworak/dfg_3dviewer#34]
Some survey participants claimed that their model were roated by 90 degrees, however currently it is hard to estimate the degree of the rotation tool in our viewer.

"After the model is uploaded, it is possible to rotate it, but there is no possibility to give an exact figure - for example 90 degrees. This makes it difficult to rotate properly.""

**Comment by thedworak** [comment]
That's the problem of different 3D modelling software and/or exporting options when XYZ axes are changed into XZY manner. Interchangeable format or standard would solve this problem, but people won't stop using dedicated formats.

**Comment by thedworak** [comment]
That's the reason why we introduced the possibility of rotating, moving and scaling models.
