### ISSUE TITLE
[!] Bug: Corrupted display of thumbanails

### ISSUE THREAD

**Issue by igorbajena** [thedworak/dfg_3dviewer#35]
Some thumbnails seems to be corrupted. What is shown is just an icon of invalid file:

![image](https://user-images.githubusercontent.com/109960112/232976245-934baedf-5416-4d3c-80bb-567ba0f769b6.png)

Automatic renders are created in all cases. Links to the problematic entries:
https://3d-repository.hs-mainz.de/wisski/navigate/2150/view
https://3d-repository.hs-mainz.de/wisski/navigate/1529/view
https://3d-repository.hs-mainz.de/wisski/navigate/1535/view
https://3d-repository.hs-mainz.de/wisski/navigate/1619/view

**Comment by thedworak** [comment]
That's the problem I raised many times as Drupal saves it with %20 encoded names. We stated users should not use whitespaces in filenames as it creates multiple problems.

**Comment by ClemensBeck** [comment]
@igorbajena Please reupload the files without spaces in the name
