### ISSUE TITLE
[!] Bug: Support of WRL file

### ISSUE THREAD

**Issue by igorbajena** [thedworak/dfg_3dviewer#36]
Similar problem like with Blender file. We have one entry, when someone tried it out, but it is not working at all. More investigation is needed, in worst case we can remove it from the list of supported formats.
https://3d-repository.hs-mainz.de/wisski/navigate/1679/view

![image](https://user-images.githubusercontent.com/109960112/232977377-8806129f-d2c7-42f8-a4b4-d6ee5c25095b.png)

**Comment by thedworak** [comment]
It won't work, there is no library for three.js and it's pretty rare format. I haven't hear about this before.

**Comment by igorbajena** [comment]
WRL format was deleted from the upload file descirption, from the list of supported formats and from our Guidelines. The entry with this format was deleted.
