### ISSUE TITLE
Bug: conversion to gltf didn't work

### ISSUE THREAD

**Issue by igorbajena** [thedworak/dfg_3dviewer#40]
Yesterday I've tried to upload one of the upgraded models of synagogues from students, but it didn't work properly. I've got message, that gltf conversion didn't happen and dae format will be loaded, but I have no textutes:
![image](https://user-images.githubusercontent.com/109960112/234659746-c7655e62-538b-4a76-8e7e-68d54f35e170.png)
https://3d-repository.hs-mainz.de/wisski/navigate/2180/view?wisski_bundle=bd3d7baa74856d141bcff7b4193fa128

The same problem was for rar file with obj package.
Despite of that I couldn't upload ZIP file. Processing was stopped in the middle without any notification, file was not uploaded to the server.
![image](https://user-images.githubusercontent.com/109960112/234660445-9f219ccc-0f3e-4d6e-860b-9570085a6b38.png)
![image](https://user-images.githubusercontent.com/109960112/234660479-770b0401-2a43-474d-8aca-4563365c1467.png)
https://3d-repository.hs-mainz.de/wisski/navigate/2185/view?wisski_bundle=bd3d7baa74856d141bcff7b4193fa128
[Sy_Olkieniki_Model3D_IgB.zip](https://github.com/thedworak/dfg_3dviewer/files/11335894/Sy_Olkieniki_Model3D_IgB.zip)

**Comment by thedworak** [comment]
This FBX file was uploaded without textures so it will only have default material colors
![image](https://user-images.githubusercontent.com/96061043/236147593-aa2b271e-0ee4-4382-b673-fec60b6af710.png)

**Comment by thedworak** [comment]
Someone deleted PHP zip extension, so I had to install it again:
https://3d-repository.hs-mainz.de/wisski/navigate/2185/view?wisski_bundle=bd3d7baa74856d141bcff7b4193fa128

**Comment by ClemensBeck** [comment]
Many thanks, now it's working again!

**Comment by thedworak** [comment]
As I mentioned many times you need to upload files that naming of textures are done i proper way. It won't guess which texture should be loaded if there would be wrong names, containing forbidden chars or non-existent paths.
Have a look at mtl file: map_Ka STGER800_SP_Textures/Stonework - 07 -opt.jpg

**Comment by ClemensBeck** [comment]
@igorbajena Will add a line to the guidelines

**Comment by ClemensBeck** [comment]
@igorbajena Since I'm migrating all the isuses to the new github repo. Is this isue still open?

**Comment by ClemensBeck** [comment]
@igorbajena All right. I will open a new issue in the new repo: https://github.com/slub/dlf-3d-viewers/issues/22
