### ISSUE TITLE
Bug: Clipping planes do not clip whole model

### ISSUE THREAD

**Issue by igorbajena** [thedworak/dfg_3dviewer#41]
I've noticed that in some cases clipping planes do not work properly. Some geometry is left behind like in case below:
https://3d-repository.hs-mainz.de/wisski/navigate/31/view
![image](https://user-images.githubusercontent.com/109960112/235451252-e022f54a-1a0e-4ff4-8631-d11a5a1fd7da.png)

I am pretty sure, that it worked better in the past, while I have screenshot of the same model in repository from October:
![image](https://user-images.githubusercontent.com/109960112/235451447-91c5c9d8-d7ca-4a2a-b69a-ae3d82831038.png)

**Comment by thedworak** [comment]
Could you please recheck it? I just tested it and it looks good for me. Maybe you did some changes before what caused this issue?
![image](https://user-images.githubusercontent.com/96061043/236146722-e78dcc05-1d97-4b43-ab2b-1986d2e5f982.png)

**Comment by igorbajena** [comment]
Today it works without flaws. I am pretty sure that I haven't done any changes, while all I needed was a new 3D screenshot of this particular model. I will check clipping planes feature on few more examples, if it won't happen again issue can be closed.
