### ISSUE TITLE
Feature: URLs to external documentation

### ISSUE THREAD

**Issue by igorbajena** [thedworak/dfg_3dviewer#46]
Request made by Jan Lutteroth:

![image](https://github.com/thedworak/dfg_3dviewer/assets/109960112/b7b09a5b-e3c2-4afd-ae41-e739fdf6adba)

**Comment by ClemensBeck** [comment]
@igorbajena Can you do this?

**Comment by ClemensBeck** [comment]
@igorbajena added this
