### ISSUE TITLE
Feature: ORCID adapter for data retrieval (To be dicussed with Sander) @???

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/dfg_3dviewer#5]
* [ ] Development of ORCID adapter for data retrieval

Comment by Igor: Fot the developemnt we need a person with programming skill in php, who could actively particpate in the process. We can get support from WissKI heckathon group (leader is Robert Nasarek)

Comment by Clemens: Already existing in Jena?

**Comment by igorbajena** [comment]
Question of who could integrate ORCID API for use of WissKI system. After talks with Robert Nasarek, it should be possible. The first problem of saving retrieved data is not longer a problem, while Beatrycze implemented data retrieval from ORCID on SLUB side also.
