### ISSUE TITLE
Add more options for creator/author of models 

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/dfg_3dviewer#53]
* [ ] @igorbajena  Add more options for keywording creator/authors of models
* [ ] @igorbajena Add clearer distinctions betwen creathor/author etc.  
Comment from project partner: "Many objects also have a maker. Is this then the author? Or is the author the creator of the 3D model? More options for keywording are still missing here."

**Comment by igorbajena** [comment]
The new data model should present difference between author and creator more clear. I will try to implement it also here.

What "maker" means? Is it maker of real object? If so, it is possible to add it "Object" section. If it is about digital model, then I need a hint what is "maker" role in the process,

We haven't used in repository term "keywording", but I assume it is about creators roles. I can add more roles, but I need to hear what exactly is missing. I put there everything what came to my mind.

**Comment by ClemensBeck** [comment]
I asked again what exactly is meant by this and got an answer. By maker, they mean the producer of the digitised object. For example, if Michelangelo created the David, but someone creates a 3D model of it. Who is the author then? Michelangelo or the other person? There must be the possibility to enter both pieces of information.

**Comment by ClemensBeck** [comment]
Moved to: https://github.com/slub/dlf-3d-viewers/issues/13
