### ISSUE TITLE
Add CityGML conversion

### ISSUE THREAD

**Issue by thedworak** [thedworak/dfg_3dviewer#65]

**Comment by ClemensBeck** [comment]
I forgot to ask in the jour fixe: How is the actual status of the CityGML conversion?

**Comment by thedworak** [comment]
@ClemensBeck it's implemented now and should be tested. You have to bear in mind the file's extension should be .gml

**Comment by ClemensBeck** [comment]
@igorbajena Could you test it after your vaccation?

**Comment by igorbajena** [comment]
I tried to upload to 3D Repository the same GML, which I sent Daniel for testing. After 40 minutes the file is still processing. For web environment if upload of the file last longer then 20 seconds (for upload in the form we don't have a progress bar), then I would say that it's not usable right now. But anyway, GML can be now upload to the viewer in our 3d repository, so further tests can be done also by others.

**Comment by ClemensBeck** [comment]
Upload of CityGML is working, Issue will be closed
