### ISSUE TITLE
Feature: Option to link Fotos and 3D-Models @Igor (?)

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/dfg_3dviewer#7]
* [ ] Option to link Fotos and 3D-Models

**Comment by igorbajena** [comment]
I don't understand idea behind. @ClemensBeck how it suppose to work?

**Comment by ClemensBeck** [comment]
@igorbajena This should work in such a way that you can, for example, insert a link to dropbox/cloud with photos in the metadata that also show the model (e.g. if you have created the models by photogrammetry and you want to refer to the "originals").
