### ISSUE TITLE
DFG-Viewer Integration: CONFIG.basePath should be able to be overridden by a container attribute

### ISSUE THREAD

**Issue by markusweigelt** [thedworak/dfg_3dviewer#70]
Similar to the model attribute "3d", it should also be possible to overwrite the basePath via HTML Attribute 

```
if(container.hasAttribute("basePath")) {
	CONFIG.basePath = container.getAttribute("basePath");
}
```

**Comment by thedworak** [comment]
Fixes and will be updated in new release

**Comment by markusweigelt** [comment]
It would be great if the README.md included a corresponding note about which HTML attributes can be set to override the default configuration.
